import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { Glow } from '@/components/Glow';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" />
        <main className="bg-[#05072d] w-full h-full">
          <Glow classes={'left-10 top-56 bg-[#af207a]'} />
          <Glow classes={'left-[70rem] top-[30rem] bg-orange-400'} />
          {children}
        </main>
      </body>
    </html>
  );
}
